СОЗДАНИЕ КОМПОНЕНТА КНОПКИ И STORIES
AlexYuhim/my-house pull request #1
Opened 2022-05-12 19:20 UTC by AlexYuhim

2022-05-12 19:44 UTC, VYuhim requested changes
В рамках этого пул-реквеста нам нужно сверстать кнопку, 1 в 1, как на макетах.
Также давай переименуем коммит месседж, согласно конвенции именования коммитов https://www.conventionalcommits.org/ru/v1.0.0/

2022-05-12 19:44 UTC, VYuhim commented on .eslintrc
> +         "import/no-anonymous-default-export":"off",
А зачем ты отключил это правило?
Ты разобрался что оно делает?

2022-05-12 19:44 UTC, VYuhim commented on src/App.js
>  function App() {
давай переименуем файлик App.js -> App.jsx (будем jsx писать в jsx файлах 🙂 )

2022-05-12 19:44 UTC, VYuhim commented on src/components/button/button.icons.jsx
> +const IconsLup = () => {
Не получилось через SVGR импортировать?
Вот пример: https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs

2022-05-12 19:44 UTC, VYuhim commented on src/components/button/button.jsx
> +    <button onClick={handleClick} type={type} style={style}>
Давай handleClick переименуем в onClick. Существует соглашение среди реакт-разработчиков об именовании хандлеров: имена хандлеров начинаются с "on":
onClick, onChange, onEvent и т.д. + если мы расширяем кнопку, будет логично сохранить ее интерфейсы

По поводу инлайна в css я уже сказал почему это зло.
Что такое специфичность: https://developer.mozilla.org/ru/docs/Web/CSS/Specificity
Что такое БЭМ: https://ru.bem.info/methodology/css/
Либа, которую нужно использовать: https://ru.bem.info/technologies/bem-react/classname/

2022-05-12 19:44 UTC, VYuhim commented on src/components/button/button.jsx
> +  borderRadius = '',
borderRadius, color, background, width и height должны определяться с помощью пропертей View и Size, каждому View и Size должны соответствовать свои классы в css (view и size это модификаторы по БЭМУ).
Если мы захотим прокинуть дополнительные стили к нашей кнопке, то это можно будет сделать через проперти className, давай добавим его сюда.

2022-05-12 19:44 UTC, VYuhim commented on src/components/button/button.jsx
> +  label = 'Click my',
Вместо label тут лучше воспользоваться children, чтобы не нарушать текущий интерфейс кнопки, см тут: https://ru.reactjs.org/docs/composition-vs-inheritance.html#containment

2022-05-12 19:44 UTC, VYuhim commented on src/components/button/button.jsx
> +  let scale = 1;
Менять размер кнопки нужно не скейлами, а css-классами с соответствующими height, font-size, line-height и т.д.
Скейлы они масштабируют компонент целиком, изменяя слой, на котором он отрендерен (про критический путь рендера почитаем потом), что дорого и в целом неправильно - всплывут баги, например, когда ты захочешь задать кнопке высоту 100px через css - тебе нужно будет учитывать еще и коэффициент скейла, что не удобно и т.д.

2022-05-12 19:44 UTC, VYuhim commented on src/components/button/button.jsx
> +    padding: `${scale * 0.5}rem ${scale * 1}rem`,
Относительные единицы измерения в css лучше не использовать (ремы и емы). Они менее явные, чем пиксели (и мне они не нравятся 😊).

2022-05-12 20:16 UTC, AlexYuhim commented on .eslintrc
> +         "import/no-anonymous-default-export":"off",
import/no-anonymous-default-export 
Сообщает, является ли экспорт модуля по умолчанию безымянным.
Обеспечивает,  чтобы экспорты по умолчанию были названы.
Правило включил, экспорт именовал

2022-05-13 05:44 UTC, VYuhim commented on .eslintrc
> +         "import/no-anonymous-default-export":"off",
отлично :)

2022-05-13 07:14 UTC, AlexYuhim commented on src/App.js
>  function App() {
Готово)

2022-05-13 07:17 UTC, AlexYuhim commented on src/components/button/button.icons.jsx
> +const IconsLup = () => {
нет, не получается. попробую поработать с другими форматами.

2022-05-13 07:34 UTC, VYuhim commented on src/components/button/button.icons.jsx
> +const IconsLup = () => {
Надо разобраться с свг, это важно

2022-05-20 11:47 UTC, VYuhim requested changes

2022-05-20 11:47 UTC, VYuhim commented on src/services/bem.js
> +// const block = bem('block');
надо бы комменты лишние дропнуть

2022-05-20 11:47 UTC, VYuhim commented on src/components/button/button.jsx
> +const Button = ({
Давай файлы для компонентов с большой буквы называть (Как компонент):
`Button.css`
`Button.jsx`
`Button.stories.jsx`
и т.д. Так будет легче искать нужные файлы

2022-05-20 11:47 UTC, VYuhim commented on src/components/button/button.icons.jsx
> +const IconsLup = () => {
А что это?

2022-05-20 11:47 UTC, VYuhim commented on src/components/button/button.jsx
> +  children = 'button',
давай уберем значение по умолчанию для children, кажется, оно не нужно.

2022-05-20 11:47 UTC, VYuhim commented on src/components/button/button.jsx
> +  const myClass = bem('button');
Давай создадим эту функцию за пределами компонента, чтобы она не вызывалась на каждый ререндер.

2022-05-20 11:47 UTC, VYuhim commented on src/components/button/button.jsx
> +  const myClass = bem('button');
и myClass как-то слишком топорно, давай block назовем?
`const block = bem('button')`

2022-05-20 11:47 UTC, VYuhim commented on src/components/button/button.jsx
> +        {/* {icon} */}
лишние комментарии

2022-05-20 11:47 UTC, VYuhim commented on src/components/button/button.jsx
> +      <div className=''>
Лишний див и пустой className

2022-05-20 11:47 UTC, VYuhim commented on src/components/button/button.jsx
> +    'basic_icon',
Что такое вариант?

2022-05-21 13:50 UTC, AlexYuhim commented on src/services/bem.js
> +// const block = bem('block');
ок уже делаю.

2022-05-21 13:50 UTC, AlexYuhim commented on src/components/button/button.jsx
> +const Button = ({
Хорошо

2022-05-21 13:54 UTC, AlexYuhim commented on src/components/button/button.icons.jsx
> +const IconsLup = () => {
это компонент который возвращает svg изображение, просто пробовал разные варианты прикрутить эту иконку.... опыта то нету вот и ....... вот))))

2022-05-21 13:57 UTC, AlexYuhim commented on src/components/button/button.jsx
> +  children = 'button',
Хорошо уберу, оно здесь для того чтобы кнопка которая по умолчанию, не была такой маленькой .....

2022-05-21 16:19 UTC, VYuhim approved these changes

2022-05-21 16:20 UTC, merged