feat(services): реализация сервисной  функции bem.js
AlexYuhim/my-house pull request #5
Opened 2022-05-17 11:13 UTC by AlexYuhim

2022-05-17 12:29 UTC, VYuhim requested changes
Давай перепишем без использования arguments.

2022-05-17 12:29 UTC, VYuhim commented on src/services/bem.js
> +  argBem = joinArgs(...arguments);
А почему ты сразу не присвоил argBem это значение?

2022-05-17 12:29 UTC, VYuhim commented on src/services/bem.js
> +  argBem = joinArgs(...arguments);
И мы же решили, что тут не нужно джойнить аргументы, пользователь сам передает имя блока при вызове функции.

2022-05-17 12:29 UTC, VYuhim commented on src/services/bem.js
> +function bem() {
Давай не использовать ключевое слово arguments. Его использование считается плохой практикой т.к. непонятно какие аргументы ожидает функция и нужно ли в нее вообще что-либо передавать.
arguments допускается использовать только в тех случаях, когда у тебя заранее неизвестно кол-во аргументов функции (это не наш кейс), и то спред аргументов в массив - является более предпочтительным.

2022-05-17 12:45 UTC, AlexYuhim commented on src/services/bem.js
> +  argBem = joinArgs(...arguments);
Удалил джоин аргументов  внешней функции. 
объявление переменной argBem и такое присвоение это следствие разных вариантов кода,

2022-05-17 12:47 UTC, AlexYuhim commented on src/services/bem.js
> +  argBem = joinArgs(...arguments);
т.к. в нашем кейсе больше не используется  джоин аргументов внешней функции. данная переменная удалена.

2022-05-17 12:49 UTC, AlexYuhim commented on src/services/bem.js
> +function bem() {
Хорошо. 
реализовал спред аргументов в массив  во внутренней функции, переписал код  без использования ключевого слова arguments

2022-05-17 13:05 UTC, VYuhim requested changes

2022-05-17 13:05 UTC, VYuhim commented on src/services/bem.js
> +function bem(argBlock) {
а зачем префикс arg? Может просто block назовем?

2022-05-17 13:05 UTC, VYuhim commented on src/services/bem.js
> +  return function (...args) {
Мне кажется, или замена `arguments` на `...args` в этом кейсе не делает код более понятным?)
Люди чаще читают код, чем его пишут. Сейчас не понятно что нужно передать в эту функцию.
Что будет если я передам сюда больше 2х аргументов?

Предлагаю так:
```
return function (elementOrMod, mod) {
...
}

2022-05-18 10:19 UTC, VYuhim requested changes

2022-05-18 10:19 UTC, VYuhim commented on src/services/bem.js
> +    resultString = block + element + mod;
Кажется, что эта переменная рудимент - можно вернуть сразу конкатинацию строк:
```return block + element + mod```

2022-05-18 10:19 UTC, VYuhim commented on src/services/bem.js
> +    function valueModFromObj(obj, element) {
Если эту функцию создать внутри функции bem (рядом с resultString), тогда она не будет создаваться заново на каждый вызов функции block(), а создастся 1 раз и будет браться из замыкания, что увеличит производительность. Давай поправим.

2022-05-18 13:43 UTC, merged