Feat/input
AlexYuhim/my-house pull request #6
Opened 2022-05-23 15:39 UTC by AlexYuhim

2022-05-23 18:16 UTC, VYuhim requested changes
Уже лучше, но есть нюансы.

2022-05-23 18:16 UTC, VYuhim commented on src/components/Button/Button.jsx
> +  /** Вид отображаение */
очепятка: Вид отображаениЕ

2022-05-23 18:16 UTC, VYuhim commented on src/components/Button/Button.jsx
>    type: PropTypes.string,
давай на mdn посмотрим каким может быть атрибут type у кнопки и забьем возможные значения через oneOf

2022-05-23 18:16 UTC, VYuhim commented on src/components/Input/Input.css
> +input {
Не рекомендуется навешивать глобальные стили на тэги. Ты так добавишь стилей ко всем инпутам, а не только к нашему, который мы разрабатываем. Давай инкапсулируем стили классом.

2022-05-23 18:16 UTC, VYuhim commented on src/components/Input/Input.css
> +span {
Тот же коммент, что и к селектору `input`

2022-05-23 18:16 UTC, VYuhim commented on src/components/Input/Input.css
> +  padding: 0;
у дива разве есть padding и margin?

2022-05-23 18:16 UTC, VYuhim commented on src/components/Input/Input.jsx
> +      <fieldset disabled={disabled} className={block('fiedsetgrup')}>
fieldset это немного не то.
https://developer.mozilla.org/ru/docs/Web/HTML/Element/fieldset

Нам же нужно сделать так, чтобы лейбл у инпута в состоянии фокус заезжала на верхнюю рамку. Посмотри css свойства `transform` и `transition`
https://developer.mozilla.org/ru/docs/Web/CSS/transform
https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Transitions

2022-05-23 18:16 UTC, VYuhim commented on src/components/Input/Input.jsx
> +  status: PropTypes.oneOf(['error', 'warning']),
давай лучше передавать объект статуса целиком:
`status={{ type: 'error', message: 'Упс, ошибочка вышла...' }}`
Тогда у нас не будет кесойв, когда status передан, а сообщение - нет.
Не забудь посмотреть как с помощью propTypes типизировать поля объектов

2022-05-23 18:16 UTC, VYuhim commented on src/components/Input/Input.jsx
> +          <span className={block('error')}>{statusMessage}</span>
Смотри, у тебя тут явно дублирование. Строчки отличаются только значением элемента в функции block. У тебя же это значение лежит в переменной статус. Соответственно эти спаны можно заменить одним, убрав дублирование.

2022-05-23 18:16 UTC, VYuhim commented on src/components/Input/Input.stories.jsx
> +  placeHolder: 'Введенная информация',
Плэйсхолдер это приглашение к вводу. Можно написать: "Введите ваше имя"

2022-05-23 18:16 UTC, VYuhim commented on src/components/Input/Input.stories.jsx
> +  title: 'Example/Input',
Давай уберем `Example/`, оставим только `Input`?

2022-05-24 11:43 UTC, AlexYuhim commented on src/components/Button/Button.jsx
> +  /** Вид отображаение */
Спасибо поправил)

2022-05-24 11:43 UTC, AlexYuhim commented on src/components/Button/Button.jsx
>    type: PropTypes.string,
добавил 4 возможных типа

2022-05-24 11:43 UTC, AlexYuhim commented on src/components/Input/Input.css
> +input {
добавил класс

2022-05-24 11:43 UTC, AlexYuhim commented on src/components/Input/Input.css
> +span {
добавил класс

2022-05-24 11:44 UTC, AlexYuhim commented on src/components/Input/Input.css
> +  padding: 0;
есть, но я не правильно размышлял как это будет  здесь выглядеть....  удалил

2022-05-24 11:44 UTC, AlexYuhim commented on src/components/Input/Input.jsx
> +      <fieldset disabled={disabled} className={block('fiedsetgrup')}>
я использовал fieldset именно потому, что  в дальнейшем хотел использовать  тег legend, который позволит вставить в обводку рамки, названия какой либо группы,  в соответствии с макетом, но еще не понимаю как это сделать, как это сделать с css свойствами transform and transition тоже не понятно.

2022-05-24 11:45 UTC, AlexYuhim commented on src/components/Input/Input.stories.jsx
> +  title: 'Example/Input',
ок, убрал

2022-05-24 11:55 UTC, AlexYuhim commented on src/components/Input/Input.stories.jsx
> +  placeHolder: 'Введенная информация',
В stories  с вводом имени поправил, но учитывая макет,  инпут может быть использован, как и при вводе имени при регистрации, так и при выборе города, поэтому не понятно какая информация будет введена в поле.

2022-05-24 13:16 UTC, AlexYuhim commented on src/components/Input/Input.jsx
> +  status: PropTypes.oneOf(['error', 'warning']),
немного не уверен правильно ли я тебя понял, но поменял .....

2022-05-24 13:16 UTC, AlexYuhim commented on src/components/Input/Input.jsx
> +          <span className={block('error')}>{statusMessage}</span>
да верно, реализовал все в одной строчке кода

2022-05-26 06:40 UTC, VYuhim commented on src/components/Input/Input.stories.jsx
> +  placeHolder: 'Введенная информация',
(я имел в виду только сторю :) )

2022-05-26 07:00 UTC, VYuhim requested changes

2022-05-26 07:00 UTC, VYuhim commented on src/components/Input/Input.jsx
> +  /** Икоонка перед текстом в инпуте */
икООнка

2022-05-26 07:00 UTC, VYuhim commented on src/components/Input/Input.jsx
> +          id='name'
а если нам понадобится тут ввести не имя, а фамилию?)

2022-05-26 07:00 UTC, VYuhim commented on src/components/Input/Input.jsx
> +        <label htmlFor='name' className={block('placeholder')}>
Для корректной работы htmlFor, id, на который ссылается label должен быть уникальным на странице. У тебя компонент, в котором id захардкожен. Соответственно каждый раз, когда мы будем использовать этот комопнент - будет появляться инпут с id "name", а все label будут ссылаться на первый инпут на странице с таким id.

Для решения этой проблемы можно не указывать htmlFor у лейбла и обернуть input в label. Тогда при любом клике на то, что внутри тега label - фокус будет попадать на input.

2022-05-26 07:00 UTC, VYuhim commented on src/components/Input/Input.jsx
> +  id: PropTypes.string,
лишний пропс, давай уберем

2022-05-26 07:00 UTC, VYuhim commented on src/components/Input/Input.jsx
> +  label: PropTypes.string,
забыл комментарий :)

2022-05-26 07:00 UTC, VYuhim commented on src/components/Input/Input.jsx
> +  type: PropTypes.string,
Тут у нас могут быть только текстовые типы (Числовой должен быть сделан иначе). В связи с этм, предлагаю тут через oneOf описать ["text", "password"]

2022-05-26 07:00 UTC, VYuhim commented on src/components/Input/Input.jsx
> +  /** тип поля инпута */
а почему некоторые комменты начинаются с заглавной буквы, а некоторые - нет?

2022-05-26 07:00 UTC, VYuhim commented on src/components/Input/Input.jsx
> +  placeHolder = ' ',
тут лучше просто ничего не передавать по умолчанию

2022-05-26 07:02 UTC, VYuhim commented on src/components/Input/Input.jsx
> +  status: PropTypes.oneOf(['error', 'warning']),
Поменял правильно, но для валидации лучше использовать PropTypes.shape({})
https://ru.reactjs.org/docs/typechecking-with-proptypes.html

2022-05-26 07:03 UTC, VYuhim commented on src/components/Input/Input.jsx
> +      <fieldset disabled={disabled} className={block('fiedsetgrup')}>
Вот видосики, посмотри их и попробуй сам сделать. Если не получится - созвонимся, сделаем вместе.
https://www.youtube.com/watch?v=yZFg3cuq_LU
https://www.youtube.com/watch?v=uQEGUpsnqsw

2022-06-05 14:22 UTC, VYuhim requested changes
Верстка не соответствует макетам + есть бага, когда введешь текст, а затем его удаляешь - лейбл не возвращается на исходное место
<img width="639" alt="Снимок экрана 2022-06-05 в 17 11 19" src="https://user-images.githubusercontent.com/41004335/172055195-a15c149f-7f29-493b-97c2-80a426e0c412.png">
<img width="683" alt="Снимок экрана 2022-06-05 в 17 09 51" src="https://user-images.githubusercontent.com/41004335/172055218-7de
<img width="656" alt="Снимок экрана 2022-06-05 в 17 10 54" src="https://user-images.githubusercontent.com/41004335/172055223-7ccb87b5-03cc-40f0-bd3f-8eb24c151b81.png">
7824f-96fc-467c-8fd3-44950826cea7.png">

2022-06-05 14:22 UTC, VYuhim commented on src/components/Input/Input.css
> +  font-family: 'Montserrat', Courier, monospace;
Шрифты нужно 1 раз к body подключить, в остальных компонентах они унаследуются.

2022-06-05 14:22 UTC, VYuhim commented on src/components/Input/Input.jsx
> +          <div className={block('label')}> {label} </div>
тут пробелы лишние между дивом и {label}

2022-06-05 14:22 UTC, VYuhim commented on src/components/Input/Input.css
> +  transition-duration: 500ms;
Пол секунды слишком долго, людей обычно бесят долгие транзишны, лучше больше 250ms не ставить

2022-06-05 14:22 UTC, VYuhim commented on src/components/Input/Input.jsx
> +        {hasPrefix && <span className={block('prefix')}>{prefix}</span>}
лучше контейнером сделать тэг label
сейчас при клике на prefix инпут в фокус не берется, хотя по верстке он (иконка) находится внутри инпута.

2022-06-05 14:22 UTC, VYuhim commented on src/components/Input/Input.jsx
> +      {status && <span className={block(status.type)}>{status.message}</span>}
этот span нужно засунуть внуть коньейнера с инпутом, чтобы он небыл самостоятельным блоком, иначе поедет верстка, когда ты этот инпут засунешь в flex контейнер какой-нибудь.
Также такие штуки лучше позиционировать абсолютно, иначе они будут двигать соседние блоки при появлении

2022-06-06 18:42 UTC, AlexYuhim commented on src/components/Input/Input.css
> +  font-family: 'Montserrat', Courier, monospace;
поправил

2022-06-06 18:42 UTC, AlexYuhim commented on src/components/Input/Input.jsx
> +          <div className={block('label')}> {label} </div>
удалил

2022-06-06 18:42 UTC, AlexYuhim commented on src/components/Input/Input.css
> +  transition-duration: 500ms;
хорошо, поправил

2022-06-06 18:43 UTC, AlexYuhim commented on src/components/Input/Input.jsx
> +        {hasPrefix && <span className={block('prefix')}>{prefix}</span>}
точно, как я сам этого не понял?

2022-06-06 18:43 UTC, AlexYuhim commented on src/components/Input/Input.jsx
> +      {status && <span className={block(status.type)}>{status.message}</span>}
Готово

2022-06-07 18:40 UTC, VYuhim commented on src/components/Input/Input.css
> +body {
давай создадим файлик `src/styles/main.css`
и туда будем складывать все подобные стили?
Там же можно и normalize.css подключить.
Чтобы стили из src/styles/main.css приминились в сторибуке их нужно импортировать в `.storybook/preview.js`

2022-06-07 18:40 UTC, VYuhim commented on src/components/Input/Input.jsx
> +  onChange = (e) => {
ты зачем тут onChange переопределил ?)
Как же мы его теперь из пропсов прокидывать будем?

2022-06-12 12:56 UTC, merged